pip install --upgrade build
python -m build
pip install --upgrade twine
create .pypirc in C:\Users\[Computer Name] and insert
    [pypi]
    username = __token__
    password = pypi-<token>
twine upload -r pypi dist/* -> in directory angkapy